language: python
python:
  - "2.7"

# Short duration job, use the container/without sudo image as it boots faster
sudo: false
# Use the latest Travis images since they are more up to date than the stable release.
group: edge

cache:
  directories:
    - "~/.platformio"

env:
  - BOARD=teensy20 PLATFORMIO_CI_SRC=examples/DimmerWithMaster
  - BOARD=teensy20 PLATFORMIO_CI_SRC=examples/TeensyDMXSend
  - BOARD=teensy20 PLATFORMIO_CI_SRC=examples/TeensyDMXRecv

  - BOARD=teensy20pp PLATFORMIO_CI_SRC=examples/DimmerWithMaster
  - BOARD=teensy20pp PLATFORMIO_CI_SRC=examples/TeensyDMXSend
  - BOARD=teensy20pp PLATFORMIO_CI_SRC=examples/TeensyDMXRecv

  - BOARD=teensylc PLATFORMIO_CI_SRC=examples/DimmerWithMaster
  - BOARD=teensylc PLATFORMIO_CI_SRC=examples/TeensyDMXSend
  - BOARD=teensylc PLATFORMIO_CI_SRC=examples/TeensyDMXRecv

  - BOARD=teensy30 PLATFORMIO_CI_SRC=examples/DimmerWithMaster
  - BOARD=teensy30 PLATFORMIO_CI_SRC=examples/TeensyDMXSend
  - BOARD=teensy30 PLATFORMIO_CI_SRC=examples/TeensyDMXRecv

  - BOARD=teensy31 PLATFORMIO_CI_SRC=examples/DimmerWithMaster
  - BOARD=teensy31 PLATFORMIO_CI_SRC=examples/TeensyDMXSend
  - BOARD=teensy31 PLATFORMIO_CI_SRC=examples/TeensyDMXRecv

  - BOARD=teensy35 PLATFORMIO_CI_SRC=examples/DimmerWithMaster
  - BOARD=teensy35 PLATFORMIO_CI_SRC=examples/TeensyDMXSend
  - BOARD=teensy35 PLATFORMIO_CI_SRC=examples/TeensyDMXRecv

  - BOARD=teensy36 PLATFORMIO_CI_SRC=examples/DimmerWithMaster
  - BOARD=teensy36 PLATFORMIO_CI_SRC=examples/TeensyDMXSend
  - BOARD=teensy36 PLATFORMIO_CI_SRC=examples/TeensyDMXRecv

install:
  - pip install -U platformio

script:
  - platformio ci --lib="." --board=$BOARD
